spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/Downloads/nylonmusk/datajpa
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
      hibernate:
       ddl-auto: create
      properties:
        hibernate:
#          dialect: org.hibernate.dialect.Oracle12cDialect
          # show_sql: true
          format_sql: true

    # page 글로벌 설정
    data:
      web:
        pageable:
          default-page-size: 10
          max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace